version: 2.1

orbs:
    mac-permissions: bytesguy/macos-permissions@dev:alpha

jobs:
  build-test:
    macos:
      xcode: 11.7
    steps:
        - checkout
        - run: echo 'chruby ruby-2.7' >> ~/.bash_profile
        - mac-permissions/add-mac-uitest-permissions
        - run: bundle install
        - run: bundle exec fastlane testandbuild

workflows:
    verify:
        jobs:
            - build-test